In [ ]:
import sys

# This should be different on your machine - I've deliberately used a deprecated python version
# This should cause a couple of things to pop up in the diff when you run this notebook.

# It should also crop up in the notebook itself - it saves the python version in the metadata.
print(sys.version)

3.9.23 | packaged by conda-forge | (main, Jun  4 2025, 18:02:02)
[Clang 18.1.8 ]

In [ ]:
# Sometimes the diff will show you where the code has changed:
# *** DELETE THIS LINE ***

def my_function():
    print("This is a function that does something.")

In [ ]:
# Sometimes it shows you where the output has changed
import pandas as pd
pd.set_option('display.max_rows', 30) # DELETE THIS LINE BEFORE RUNNING - it just configured how many rows pandas will display

df = pd.DataFrame({
    "A": range(30),
    "B": range(30, 60),
    "C": range(60, 90)
})

df

     A   B   C
0    0  30  60
1    1  31  61
2    2  32  62
3    3  33  63
4    4  34  64
5    5  35  65
6    6  36  66
7    7  37  67
8    8  38  68
9    9  39  69
10  10  40  70
11  11  41  71
12  12  42  72
13  13  43  73
14  14  44  74
15  15  45  75
16  16  46  76
17  17  47  77
18  18  48  78
19  19  49  79
20  20  50  80
21  21  51  81
22  22  52  82
23  23  53  83
24  24  54  84
25  25  55  85
26  26  56  86
27  27  57  87
28  28  58  88
29  29  59  89